### PR TITLE
docs: upd links to rfc9562

### PR DESCRIPTION
**Pull request by alexbozhenko**
RFC 9562 obsoletes RFC 4122.
https://datatracker.ietf.org/doc/html/rfc9562#name-update-motivation

### CODE REVIEW

**Comment by alexbozhenko** [comment]
alos, could someone update the description of the github repo to include new rfc number?

**Comment by alexbozhenko** [comment]
@bradleypeabody: is it the right thing to do?
Also, number of other places also link to the draft:
https://sourcegraph.com/search?q=context:global+https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format+-path:vendor+count:all&patternType=keyword&sm=0

**Comment by alexbozhenko** [comment]
And not sure if all other references to 4122 should be updated 
https://sourcegraph.com/search?q=context:global+4122+repo:%5Egithub%5C.com/google/uuid%24+&patternType=keyword&sm=0

**Review by bormanp — COMMENTED** [review]
Were there any changes of what was in the previous two documents?  If so we may need to update the code.

**Comment by bormanp** [comment]
The constant RFC4122 cannot be changed though a new constant could be defined to be equal with it.  Probably `Standard = RFC4122` (or the other way around).  Not sure it is worth it.  There probably should be a note in the documentation that 9562 obsoletes 4122 so it makes sense why RFC4122 is the name of the standard variant.

I don't think the code comments need updating nor do the tests.  For backwards compatibility I believe `Variant.String` will still need to return the string "RFC4122".

**Comment by bradleypeabody** [comment]
My suggestion would be along the lines of what @bormanp is saying - add another constant either `Standard` (or maybe just `RFC`) and/or `RFC9562` with the same value as `RFC4122` (i.e. probably just adding a separate `const RFC = RFC4122` could be enough).  And I would imagine that having Variant.String() return "RFC4122" is not really a deal breaker and that can be just left as-is until/unless there's a need to change it.

**Comment by alexbozhenko** [comment]
@bormanp @bradleypeabody thanks for your comments.
I added a new constant with the comment and had to change a couple of places in the comment to make it more consistent.
If you have suggestions how to improve wording, feel free to push to this branch(or use code suggestion in the comments), so we can merge it and move on with our lives)

**Review by bormanp — APPROVED** [review]

**Comment by alexbozhenko** [comment]
@bormanp thank you for approving! Do you know who has the merge rights?

**Pull request merged**
