### PR TITLE
feat: add Max UUID constant

### PR DESCRIPTION
**Pull request by it512**
add Max uuid

### CODE REVIEW

**Comment by bormanp** [comment]
LGTM, but please address the conventional commits error in the tests.  Thank you!

**Comment by it512** [comment]
Please give me a hint, which questions need to be corrected? Thanks!
I add go 1.18 support in go.mod

**Comment by noahdietz** [comment]
> Please give me a hint, which questions need to be corrected? Thanks! I add go 1.18 support in go.mod

Can you please revert this and send it in a separate commit? Best to keep these things separate.

**Comment by noahdietz** [comment]
I fixed the title and applied `automerge`. Bots will squash-merge the commits with the title as the commit, which conforms to the conventional commit spec.

Please remove the Go 1.18 change though.

**Comment by it512** [comment]
ok already revert . Thank you!

**Review by noahdietz — APPROVED** [review]

**Pull request merged**
